### ISSUE TITLE
build.pldb.com being blocked

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#199]
how is this even possible?

<img width="1223" alt="Screen Shot 2022-10-08 at 10 54 21 AM" src="https://user-images.githubusercontent.com/74692/194720937-e8f731ff-d525-4ccf-b67c-f7ababd7110a.png">

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

This is indeed frustrating! 😢 

Are you using a Cisco Meraki firewall? Then it is using an unusual port (8090), but this would be acceptable for a dedicated firewall, otherwise it might raise [suspicions](https://www.speedguide.net/port.php?port=8090).

Does the URL finish with something like `&blocked_categories=bc_057` as shown on [this](https://networkengineering.stackexchange.com/questions/38147/meraki-blocking-some-of-google-and-this-is-undesired) page? If so, then your firewall log should give the blocked category. The page has some suggested solutions.

Also, you are checking `http://build.pldb.com/`, rather than the secure `https` version. This is fine, as it should [automatically redirect](https://wheregoes.com/trace/20224852649/)  to the `https` version. But it would be interesting if you tried the *https* URL to see if you get a different result.

[VirusTotal](https://www.virustotal.com/gui/url/44c523135a9b3c0c6184f82845e1149c61dfd9d36693bf0802e7bd329614d667/details) is showing one security vendor as flagging the `https://build.pldb.com/` URL as a source of spam. This may be because the old `pldb.com` was also flagged for the same reason. Therefore, it might be the cause of the Meraki firewall blocking the "build" URL.

In any case, try the suggested solutions and see if this might resolve the issue for you.

Kind Regards,
Liam

**Comment by breck7** [comment]
Wow thanks for the investigation @celtic-coder ! This was at a Starbucks in Orange Country. It was clearly my fault—I didn't notice I put in "http", which explains how they could have intercepted it. Thanks!
