### ISSUE TITLE
What's the standard way of handling languages with the same name as existing languages

### ISSUE THREAD

**Issue by tif-calin** [breck7/pldb#343]
Inspired by Google's Rune language which was recently made public but there already exists [a pl named Rune](https://rune-rs.github.io/) and it predates it.

Google's will inevitably be more popular (assuming it isn't [killedbygoogle](https://killedbygoogle.com/)) but it seems kinda unfair given the other language came first.

**Comment by breck7** [comment]
Let's add both.

Let's give Google's the permalink `rune.pldb` b/c that's probably what most people will want for now. If in the future the older one becomes more popular we can revert.

Name conflicts in `title` field are fine. The only place we have to make an editorial decision is with permalinks.

And because everything is on git, we can change at any time if we make a mistake.

**Comment by tif-calin** [comment]
@breck7 so what would the other language be called? `rust-rs.pldb`?

This might be a more clearcut case this time, but wondering if we have a more in-depth solution for when this issue arises again in the future

I'm sure there's gonna be many hobby langs with the same name and having to do `lang.pldb`, `lang2.pldb`, etc doesn't seem like a good solution haha. Maybe we should consider using the ids in the file names in the future?

**Comment by breck7** [comment]
Great question @tif-calin. We have dozens of instances of this already. We usually just use something like `rust-lang`, et cetera. Our key strategy is to do everything on git, so we can always fix everything all at once in a single commit. Migrations are a piece of cake (and will be even easier as our tooling improves).

**Comment by tif-calin** [comment]
Ok fair enough. I still have concerns about how sustainable this is. I guess we can do something like `lang-YEAR`, `lang-YEAR-MM`, etc as well
