### ISSUE TITLE
boolCell keys valid values set changed ??

### ISSUE THREAD

**Issue by ghost** [breck7/pldb#360]
Just a confirmation:
Has boolCell keys changed accepted values ??
I tried using "Yes" and "yes" and both failed. 
The error message says they are still valid.
```

    _trues: Set(4) { '1', 'true', 't', 'yes' },
    _falses: Set(4) { '0', 'false', 'f', 'no' }

```

**Comment by breck7** [comment]
Yes. Made it more strict: https://github.com/breck7/pldb/blob/main/database/grammar/primitives.grammar#L13

**Comment by SRS-WRKS** [comment]
@breck7  npm run test can be misleading , (atleast for me).

Could be because of cached files not being updated/being stale ??

on my machine I run the following command
`npm install . && npm i -g cloc && npm run tsc && npm run build && npm run test && echo "COMMIT CAN BE PUSHED"
`
from mail checkout directory and it still treats Yes/yes as valid boolean values according to build log.

**Comment by breck7** [comment]
Sorry @SRS-WRKS I think the error is in the error message. I am over riding the default behavior of `boolCell` which ships in Grammar and I think that's where the error message is coming from. Investigating...

<img width="458" alt="Screen Shot 2022-12-30 at 6 25 03 PM" src="https://user-images.githubusercontent.com/74692/210097061-d03a9f67-3a59-4b6e-bdad-1dda67c46fc7.png">

**Comment by breck7** [comment]
Should be fixed
