### ISSUE TITLE
Improve build speed

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#385]
Building the static site is now taking 25s on my machine. 10x longer than I'd like.

Biggest win will be the golden rule of build langs:
[] don't rebuild things when the inputs haven't changed

Then there are other places to improve Jtree, TreeBase and Scroll to make things faster.

I'm open to rolling our own Tree Language for buildings. I have a few experiments along those lines in JTree.

I know there are plenty of great build langs and systems out there, but until there's a Tree Language for it the problem remains unsolved (because there's still things that can be taken away ;) ).

**Comment by SRS-WRKS** [comment]
@breck7 : I do agree that writing custom DSL for tree notations is a daunting task for new users (especially for people not used to lisp) and finding documentation for it is hard. Documenting DSL creation and testing it is necessary.

Many people have tried to create custom build systems, none has seen wide adoption, sadly.

But if you want to choose to build a custom build system, the number of users/adopters would be limited, realistically.

Quoting from https://suckless.org/sucks/
`As these build systems are often used to compile C programs, one has to set up a C++ compiler or Python interpreter respectively just in order to be able to build some C code.`

But a simple system that

1. Use POSIX make syntax
2. offers package kit like support for compilation flags
3. easy and useful debugging support
4. Optional configure like autodiscovery framework to create create packagekit like files for compilation
5. Disallow recursive make by default and offer simple multi directory build/dependency handling in posix make syntax

Could actually be useful. Getting new users/adopters would be pretty hard.

**Comment by breck7** [comment]
I don't care too much about external users. If it saves me 10 minutes a day and only takes me 6 hours to build, then in 2 months it will have been worth it!

**Comment by SRS-WRKS** [comment]
@breck7 : You want a build system with custom DSL in treenotation built in 6 hours (coded in 6 hours) and it should save you 10 minutes a day in runtime, compared to what is used today ??

**Comment by adriantintpilver** [comment]
Hi!, I'm not a scroll expert yet but I'm learning.
I have a question, right now every time we run the Build it regenerates each of the .js and then the .HTML even though only some of the files in things/*.pldb have been updated.
So we could see the date of the html in the site/languages folder and if that file is newer than the corresponding .pldb, just skip that creation. I think that with this we would greatly reduce file creation times in general.
If they agree, I could do a proof of concept on this to see if it can work and is it possible

**Comment by SRS-WRKS** [comment]
@adriantintpilver : Hey, please have a  look at https://github.com/breck7/scroll/issues/72

**Comment by adriantintpilver** [comment]
Great @SRS-WRKS.
I was already thinking about making a new version of _buildAndWriteFiles() in scroll.js but with this information I can make a function in PLDB that iterates through the .pldb files and only sends those that need to be generated. Without it being necessary to modify scroll at least for now.
I'm going to get to work on this, when I have something I'll tell you.

**Comment by adriantintpilver** [comment]
Hi, I was analyzing this and I have a function that compares the dates of the .pldb files in database/things and the .html files in site/languages and generates the .scroll only in cases where the .pldb is newer than the html or not there is the .html.

But I'm stuck on how to generate the .html content using the scroll-cli functions, I'm not an expert in scrolling yet and I can't find a function that does this that generates the .html content from the .scroll or from the .pldb.

I keep looking at it, but if it occurs to you where to guide me, I would appreciate it.

Thank you!
Regards!

**Comment by adriantintpilver** [comment]
Hi! @breck7 do you have any help about this question? i don't found this yet.

**Comment by breck7** [comment]
Build system has been largely removed, since it is now primarily a dynamic site.
