### ISSUE TITLE
Language Count Discrepancy

### ISSUE THREAD

**Issue by celtic-coder** [breck7/pldb#55]
Hi Breck (@breck7),

The list [All Languages](https://pldb.com/lists/languages.html) states that the PLDB has 4,058 languages:

![All-Languages-count](https://user-images.githubusercontent.com/11787866/188229626-ea221c6c-55f5-42b3-a46c-a03bcff92af4.png)

Doing a search from the home page, with nothing in the search box, gives a different count for the languages:

https://edit.pldb.com/search?q=#

![Blank-search-count](https://user-images.githubusercontent.com/11787866/188230290-1ba09fef-80f2-4c6e-ac7c-cb061204f69a.png)

On my local copy of the repo, when I search the *.pldb* files in the _/things/_ folder for the "title" keyword, which the [CSV Documentation](https://pldb.com/docs/csv.html) says has 100% coverage, then I get the same result:

![4671-files-found](https://user-images.githubusercontent.com/11787866/188231655-0ef03eef-037b-4733-aac8-4d39644b23e5.png)

There is, however, a further issue with the _search_ results. When I search on the page for the **$** language, for example, I get two matches rather than one (the URL https://pldb.com/languages/dollar-sign.html is the same for both).

Here is the first match:

![Dollar-Sign-first-result](https://user-images.githubusercontent.com/11787866/188237735-db384565-c82c-44bf-962e-8186b682078b.png)

... and here is the second:

![Dollar-Sign-second-result](https://user-images.githubusercontent.com/11787866/188238213-033593db-78f6-4d4c-95f3-a8e65ee60be1.png)

Something is getting repeated in the search results, which can be seen about halfway down the page:

![Results-getting-repeated](https://user-images.githubusercontent.com/11787866/188240064-c9238512-daaf-453e-8296-131b1ee82986.png)

I am guessing that the **4,671** count is correct, but how the results are being displayed as well as the difference with the _"All Languages"_ list would need further investigation.

Kind Regards,
Liam

**Comment by breck7** [comment]
The 2 counts are different because there are 4,671 entities, but only 4,058 of those fall into categories I classify as "languages". Explained on this page:

![Screen Shot 2022-09-02 at 2 46 14 PM](https://user-images.githubusercontent.com/74692/188249245-1eec3e90-6e71-480e-b376-42ad9907530e.png)

The mapping of language vs non language is currently here: https://github.com/breck7/pldb/blob/a4ebba8ed33f87829146ccefa5014a7205bb2e49/code/utils.ts#L118

But that should move to the grammar files at some point.

The way I envision it is that we should focus on things we could call `languages`. _BUT_ we should also allow for *notable* things one degree of separation away. For example, operating systems and editors. Why? I think there's a lot we could do down the line by having a tiny bit of data on those things which are intimately connected to these languages. The one degree of separation rule keeps scope contained. So a good rule of thumb is if there's an entity like an operating system that has a wikipedia page and that page is linked to a language(s), then it's fine to add a pldb file for it.

So that is the reason why you are seeing those discrepancies. But that's not clear. I will take a look at clearing up the verbiage now.

The reason you are seeing 2 matches for $ sign is that I run 2 independent searches, one on names and one on full contents. Then I show the names up top first. That's not clear either. I will do a design pass there.

Thanks! I'll keep open until I push the design pass for your review.

**Comment by breck7** [comment]
Okay I just did a design refresh on the search results page. Also fixed a lot of little annoying things (I put a bigger search box on that page, and if you are coming from a search I refill all the search boxes with your query)

Before:
![Screen Shot 2022-09-02 at 4 24 20 PM](https://user-images.githubusercontent.com/74692/188252323-67291456-4036-494b-b70a-50595772a5b8.png)

After:
![Screen Shot 2022-09-02 at 4 25 40 PM](https://user-images.githubusercontent.com/74692/188252321-e2a80ab9-e82d-4a78-87e3-2b179de034b9.png)

**Comment by breck7** [comment]
I am going to close this one out, but please open a new one if there are issues that remain. I think we could make search really great.
