### ISSUE TITLE
Step 1: clean up the new >40 file names. Step 2: add a unit test to ensure we have no files with uppercase letters nor spaces, special chars, etc. Let's stick to a-z0-9\-

### ISSUE THREAD

**Issue by breck7** [breck7/pldb#96]
let's figure out best way to enforce reduced entropy in filenames. If we need to expand combinatorics later, we can. But let's keep it as small as possible for as long as possible, until we gain some good advantage by adding additional characters

- no spaces in filenames *.pldb
- all lowercase filenames

**Comment by celtic-coder** [comment]
Yes, having all filenames as lowercase would avoid the conflict between Windows and Unix, for example.

If you have not already done so, you might also check out the use of ".gitattributes" for CR/LF endings and ".editorconfig" for other settings in the actual file content.

Tristano (@tajmone) has a great example [here](https://github.com/pml-lang/pml-userman/pull/11) which also addresses things like trimming of trailing whitespace and ensuring that there is a closing newline character in the file.

**Comment by breck7** [comment]
Interesting @celtic-coder ! I have not done so. Wasn't aware of that. Thanks!

**Comment by tajmone** [comment]
## EditorConfig Validation (tips)

Beware that when it comes to validating EditorConfig styles consistency (e.g. via a CI services or GitHub Actions), there are a number of issues pertaining the validation tools that need to be kept in mind.

[EClint] is the oldest (and probably widest use) validation tool. The problem is that it's been declared a dead project a long time ago, contains various bugs, and now its NPM package is also reported as being unsafe to use.

The best alternative tool right now seems to be [editorconfig-checker], which is standalone binary tools written in Go:

- [editorconfig-checker Go]

For all practical purposes, when it comes to CI integration and automation, it's best used via its NPM package wrapper, since it allows to keep the tool updated:

- [editorconfig-checker NPM]

The problem with the NPM version is that it's lagging far behind the latest binary release, so (last time I checked) it wasn't updated to include some bug-fixes which made it unusable in production. Unfortunately the NPM package seems to have gone stale, but IMO if it was updated even once (to the current [editorconfig-checker Go] release) it would be usable in production and a viable substitute to [EClint] — until then, I'm afraid that EClint remains the "best" option.

For more details on the alternative validators, their bugs, etc., see alan-if/alan-docs#79



[editorconfig-checker]: https://editorconfig-checker.github.io/ "editorconfig-checker project website"
[editorconfig-checker Go]: https://github.com/editorconfig-checker/editorconfig-checker
[editorconfig-checker NPM]: https://www.npmjs.com/package/editorconfig-checker
[eclint]: https://www.npmjs.com/package/eclint

**Comment by breck7** [comment]
Also probably the cause of: https://github.com/breck7/pldb/issues/97

**Comment by breck7** [comment]
I'm going to close this but @celtic-coder if you think of one or 2 key gitattributes etc to add please feel free to open new issue or do PR
